### ISSUE TITLE
Unable to finalise hatch

### ISSUE THREAD

**Issue by nshCore** [Kitsumon/breeding-testnet#7]
## Prerequisites

Issue tracker is **ONLY** used for reporting bugs. Use [stackoverflow](https://stackoverflow.com) for supporting issues.

- [x] Have you cleared your cache?
- [x] Enter Browser name and version: .e.g. Chrome 11
Chrome Version 101.0.4951.64 
- [x] Enter Wallet name and version: XXX Version x.xx (.e.g Metamask Version 1.2.0)
MetaMask Version 10.14.6
- [ ] Enter transaction ID if any: XXX

For more information, see the [CONTRIBUTING](https://github.com/atlascity/Community/blob/master/CONTRIBUTING.md) guide....

## Features:

**Please note by far the quickest way to get a new feature is to file a Pull Request.**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

### Expected Behavior

Should finalise hatching

### Current Behavior

Does nothing console return 404 error
https://api.dev.kitsumon.net/Breeding/GetHatchStatus?requestId=44708261907329887585578241978560289862902163225695792756394117614037955843299

```
_app-7b5c4fc8ce225fc3.js:1 TypeError: Cannot read properties of null (reading 'status')
    at 588-8aa79f7316e1b990.js:1:28420
    at s (main-a8662d889c947371.js:1:91005)
    at Generator._invoke (main-a8662d889c947371.js:1:90793)
    at Generator.P.forEach.e.<computed> [as throw] (main-a8662d889c947371.js:1:91428)
    at w (588-8aa79f7316e1b990.js:1:27384)
    at u (588-8aa79f7316e1b990.js:1:29711)
  ```
    
### Steps to Reproduce

1.
2.
3.
4.

**Comment by nshCore** [comment]
Additional errors on finalisation

```
_app-7b5c4fc8ce225fc3.js:1 Error: transaction failed [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transactionHash="0x2e82f3d87d60f24a2dc737d7062dde9a9c015cb607307427d687d77b82ed61b4", transaction={"hash":"0x2e82f3d87d60f24a2dc737d7062dde9a9c015cb607307427d687d77b82ed61b4","type":2,"accessList":null,"blockHash":null,"blockNumber":null,"transactionIndex":null,"confirmations":0,"from":"0xE6029e8645A5E70b8Dc581d31A42e9b6c27e5635","gasPrice":{"type":"BigNumber","hex":"0x02fd14c7e3"},"maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x02fd14c7d7"},"maxFeePerGas":{"type":"BigNumber","hex":"0x02fd14c7e3"},"gasLimit":{"type":"BigNumber","hex":"0x11fb3e"},"to":"0x06fDc2f485F39C0fe27502e1c6A7e67129f14DA8","value":{"type":"BigNumber","hex":"0x00"},"nonce":54,"data":"0x784943840000000000000000000000000000000000000000000000000000000000000020160875833370a12eb1aaa3358c315c252b5e76a90a90a6bf5af66d97d28f736b00000000000000000000000000000000000000000000000000000000000002200000000000000000000000000000000000000000000000000000000000000300000030c30c30c30c30c30c30c30c30c30c30c30c30c30c30c30c30c30c30c30c000000000000000030c30c30c30c30c30c30c30c30c30c30c30c30c30c30c30c000000000000000000000000000000000000000000000000000000000000001f000000000000000000000000000000000000000000000000000000000000002e00000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000000d000000000000000000000000000000000000000000000000000000000000001c000000000000000000000000000000000000000000000000000000000000003c000000000000000000000000000000000000000000000000000000000000004c000000000000000000000000000000000000000000000000000000000000003e000000000000000000000000000000000000000000000000000000000000000d000000000000000000000000000000000000000000000000000000000000001c0000000000000000000000000000000000000000000000000000000000000028000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000002e516d6632794d715333314c336a7446583736354161426354525a6b64735a53775771397a5756345548485a455535000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000b436c6f7665726669656c640000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000041686fd6e9fa22b7e361c380dc30b60207de4b5f3d8fcc59a9c358f074870cb7153c6d6076fe2ce26f6392cc2bb338d136a0417b61df62afdf9847e0e7ab010c611c00000000000000000000000000000000000000000000000000000000000000","r":"0xf4427cccc9861dc9ad748c9c0a37da5fafdcb9d72aad44efd9dfd0ba8fac2980","s":"0x37e20d893fe16aade622cafbc1b98fa85024217746c4ca48f3e1aac3a74f1aaf","v":0,"creates":null,"chainId":0}, receipt={"to":"0x06fDc2f485F39C0fe27502e1c6A7e67129f14DA8","from":"0xE6029e8645A5E70b8Dc581d31A42e9b6c27e5635","contractAddress":null,"transactionIndex":26,"gasUsed":{"type":"BigNumber","hex":"0x11b59b"},"logsBloom":"0x00000000000000020000000000000000000000000000000000000000000000000000000000000000000000000000000000008000080000000000000000000000000000000000000000000000000000800000000000000000000100000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000000000000000000200000000000000020000000000000000001000000000000400000000000004000000100000000000001000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000100000","blockHash":"0xb71aac45822d2c111b4962178309ab9d1815efc49bb4b63d86a8ac0de3577286","transactionHash":"0x2e82f3d87d60f24a2dc737d7062dde9a9c015cb607307427d687d77b82ed61b4","logs":[{"transactionIndex":26,"blockNumber":26452595,"transactionHash":"0x2e82f3d87d60f24a2dc737d7062dde9a9c015cb607307427d687d77b82ed61b4","address":"0x0000000000000000000000000000000000001010","topics":["0x4dfe1bbbcf077ddc3e01291eea2d5c70c2b422b415d95645b9adcfd678cb1d63","0x0000000000000000000000000000000000000000000000000000000000001010","0x000000000000000000000000e6029e8645a5e70b8dc581d31a42e9b6c27e5635","0x000000000000000000000000c26880a0af2ea0c7e8130e6ec47af756465452e8"],"data":"0x0000000000000000000000000000000000000000000000000034ed203227022d00000000000000000000000000000000000000000000000000f53f281b6b1670000000000000000000000000000000000000000000000d92448413a9f8c9fac700000000000000000000000000000000000000000000000000c05207e9441443000000000000000000000000000000000000000000000d9244b900ca2af0fcf4","logIndex":69,"blockHash":"0xb71aac45822d2c111b4962178309ab9d1815efc49bb4b63d86a8ac0de3577286"}],"blockNumber":26452595,"confirmations":4,"cumulativeGasUsed":{"type":"BigNumber","hex":"0x3f2479"},"effectiveGasPrice":{"type":"BigNumber","hex":"0x02fd14c7e0"},"status":0,"type":2,"byzantium":true}, code=CALL_EXCEPTION, version=providers/5.6.5)
    at f.makeError (_app-7b5c4fc8ce225fc3.js:1:198018)
    at f.throwError (_app-7b5c4fc8ce225fc3.js:1:198138)
    at p.<anonymous> (_app-7b5c4fc8ce225fc3.js:1:255021)
    at Generator.next (<anonymous>)
    at s (_app-7b5c4fc8ce225fc3.js:1:233949)
 ```
 
 
 https://mumbai.polygonscan.com/tx/0x2e82f3d87d60f24a2dc737d7062dde9a9c015cb607307427d687d77b82ed61b4

**Comment by JayArrowz** [comment]
Gas limit was hit - Retry? Maybe we want to use estimateGas and set our own gas limit?

**Comment by JayArrowz** [comment]
This has been fixed?
